name: matrix
on: push
jobs:
  j1:
    strategy:
      matrix:
        node-version: [16, 18, 20]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: get code
        uses: actions/checkout@v4
      - name: install node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: install depen.
        run: npm ci
      - name: build project
        run: npm run build
